name: Docker check
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:19-alpine3.16
    steps:
      - name: log the container 
        run: node -v 
      - name: steps within docker 
        uses: docker://node:18-alpine3.16
        with:
          entrypoint: '/bin/echo'
          args: 'hello asasri' 
      - name: steps within docker 
        uses: docker://node:18-alpine3.16
        with:
          entrypoint: /usr/local/bin/node
          args: -v 
      - uses: actions/checkout@v1
      - name: check files
        run: ls -a
      - name: set permissions
        run: | 
          cd .github/workflows/
          ls -a
          chmod +x Script.sh
             
      - name: Using script
        uses: docker://node:18-alpine3.16
        with:
          entrypoint: ./script.sh
          args: "some string"          
  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports: 
        - 3001:3000
      mongo:
        image: mongo
        ports:
        - "27017:27017"   
    steps:
      - name: post a user
        run: 'curl -X POST http://localhost:3001/api/user -H ''Content-Type: application/json'' -d '' { "username": "hello","address": "dwded"}'' '
      - name: get users
        run: curl  http://localhost:3001/api/users
