name: matrix check

on: pull_request

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [6, 8, 10]
        include:
        - os: ubuntu-latest
          node-version: 8
          is_ubuntu_8: "true"
        exclude:
        - os: ubuntu-latest
          node-version: 6
        - os: windows-latest
          node-version: 10  
    env: 
      IS_ubuntu_8: ${{matrix.is_ubuntu_8}}
    runs-on: ${{matrix.os}}
    steps:
      - name: check node_version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}

      - name: log node version
        run: |
          node -v    
          echo $IS_ubuntu_8