name: Container 
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:19-alpine3.16
    steps:
      - name: log node version
        run: |
          node -v
          npx create-react-app react-app --use-npm 
          cd react-app
          npm run test
          npm install --global surge
          with:
            EMAIL: ${{secrets.EMAIL}}
            EMAIL_PASSWORD: ${{secrets.EMAIL_PASSWORD}} 
          surge token