name: Container 
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:19-alpine3.16
    steps:
      - name: log node version
        run: |
          node -v
          npx create-react-app react-app --use-npm 