name: shell cmds

on: [push]

jobs:
  run-shell-cmds:
    runs-on: ubuntu-latest
    steps:
      - name: check echo string
        run: echo "hello asasri"
      - name: checking multiline 
        run: |
          node -v
          npm -v
      - name: py cmds
        run: |
          import platform
          print
          (platform.processor())
        shell: python   
  run-powershell-cmds:
    runs-on: windows-latest
    steps:
      - name: directory of powershell 
        run: Get-Location
        run: pwd 
        shell: bash 